version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: app
    environment:
      DATABASE_URL: 'postgresql://admin:admin@postgres:5433/postgres'
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - '5433:5433'

volumes:
  pgdata_dev:
