version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: app
    environment:
      DATABASE_URL: 'postgresql://admin:admin@postgres:5432/postgres'
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata_dev:
