version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: app
    env_file:
      - .env
    ports:
      - '8000:8000'
    networks:
      - sp_network

networks:
  sp_network:
    external: true
    name: sp_network